### PR TITLE
create ap-toggle.sh

### PR DESCRIPTION
**Pull request by xcom169**
Wifi On/off script.

### CODE REVIEW

**Comment by richb-hanover** [comment]
Hi! Thank you for sending the contribution, and I'm sorry for the delay in responding. 

I cannot accept the PR as-is. It needs some documentation. At a minimum, it would be important for you to include:

- a paragraph or two that could go on the README page. It should tell a new reader why they would want to use the script, and how to invoke it. 

- The script itself should contain much of that information, so that someone can use the file without needing to find the original github repo.

Best regards,

Rich Brown

**Comment by xcom169** [comment]
Hello!

I'm afraid it's not my script. I didn't write it, so I can't comment on it
properly, however it's a really nice script for switching wifis on/off.

Regards,
Csaba Tímár

**Comment by richb-hanover** [comment]
It was my hope that these OpenWrtScripts would become popular, or even built into the standard OpenWrt stable release. But that doesn't seem to be happening, even though some of them would be useful for troubleshooting  (especially [getstats.sh](https://github.com/richb-hanover/OpenWrtScripts/blob/master/getstats.sh)) 

I think your best bet would be to publish the script on [forum.openwrt.org](https://forum.openwrt.org) - you'll get far more publicity. Best regards, Rich

**Comment by richb-hanover** [comment]
I am closing this PR. As noted in PR #6, this repo has not become as popular as I hoped. (In fact, it hardly has been noticed at all.) Consequently, I don't think it's worth the time to make make any further changes.

Thank you for the attention, and I give you my blessing to fork this if you have the energy to continue the work. Good luck, and best regards.

**Pull request closed without merging**
